@startuml
entity Користувач {
    "ім'я",
    "електронна пошта",
    "пароль"
    "тип користувача",
    "біографія",
    "дата народження",
    "адреса",
    "фото",
    "бан"

}

entity Оцінка {
    "значення"
}
entity Коментар {
    "зміст",
    "чи видалений"
}
entity Публікація {
    "назва",
    "зміст",
    "статус верифікації",
    "адреса",
    "сервіс",
    "кількість",
    "бронювання сервісу",
    "дата створення",
    "кількість місць"

}

entity Звернення {
    "зміст"
}

entity Обране {
}

entity Організація {
    "назва",
    "категорія",
    "документація",
    "власник",
    "адреса"

}

entity Категорія {
    "назва"

}

Організація "1,1"<-->"1,1" Користувач
Категорія "1,1"<-->"1,*" Публікація
Організація "1,1"<-->"0,*" Публікація
Користувач "1,1"<-->"0,*" Коментар
Публікація "1,1"<-->"0,*" Коментар
Коментар "1,1"<-->"0,*" Коментар
Користувач "1,1"<-->"0,*" Оцінка
Публікація "1,1"<-->"0,*" Оцінка
Обране "0,*"<-->"1,1" Користувач
Обране "0,*"<-->"1,1" Публікація
Користувач "1,1"<-->"0,*" Звернення
@enduml
