@startuml
left header

<font color=000 size=16><b>Назва:</b> Редагування публікації.
<font color=000 size=16><b>Учасники:</b> Користувач(представник організації), Система.
<font color=000 size=16><b>Передумови:</b> Предсавник організації авторизований, має розміщені в Системі публікації.
<font color=000 size=16><b>Результат:</b> Публікація змінена.

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Користувач|
start
: Користувач натискає кнопку "Змінити публікацію.";
|Система|

: Система отримує запит та надсилає відповідну форму;

|Користувач|

: Користувач змінює інформацію та
відправляє;


|Система|

: Система перевіряє дані;

: Система змінює публікацію;

stop;
@enduml
