@startuml
left header
<font color=000 size=18><b>Package:</b> Admin

<font color=000 size=16><b>ID:</b> UC-1
<font color=000 size=16><b>Назва:</b> Бан користувачів
<font color=000 size=16><b>Учасники:</b> Користувач, Адміністратор.
<font color=000 size=16><b>Передумови:</b> Адміністратор слідкує за порушеннями користувачів.
<font color=000 size=16><b>Результат:</b> Можливість адміністратора банити користувача за порушення правил користування Системи.
<font color=000 size=16><b>Виключні ситуації:</b>
<font color=000 size=16> EX_00: Збій відправки (не всі поля заповнені)
<font color=000 size=16><b>Основний сценарій:</b>


<font color=000 size=16><b>Основний сценарій:</b>

end header

|Користувач|
start
: Користувач натискає спеціальну кнопку "Поскаржитись на користувача";

: Користувач заповнює поля «Тип порушення» та «Опис скарги», після чого натискає кнопку «Відправити».;

: Натискає кнопку "Відправити";

|Система|
: Показується успшіне відправлення (або помилка);

note right #aaffaa
<font color=red><b> Можливо EX_00.
end note

|Адміністратор|
: Отримує повідомлення зі скаргою від користувача;

: Оброблює повідомлення на наявнітсь порушення;

: У разі неодноразового порушення Адміністратор натискає кнопку "Заблокувати користувача";

stop;
@enduml
