@startuml
left header

<font color=000 size=16><b>Назва:</b> Створення публікації.
<font color=000 size=16><b>Учасники:</b> Користувач(представник організації), Система.
<font color=000 size=16><b>Передумови:</b> Предсавник організації авторизований.
<font color=000 size=16><b>Результат:</b> Користувачам доступна нова публікація організації.
<font color=000 size=16><b>Виключні ситуації:</b>
<font color=000 size=16> EX_00: Не всі поля заповнено
<font color=000 size=16> EX_01: Дані не достовірні

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Користувач|
start
: Користувач натискає кнопку "Додати публікацію.";
|Система|

: Система отримує запит та надсилає відповідну форму;

|Користувач|

: Користувач заповнює поля (назва, фото, опису,
 інформації про заклад/місце) необхідними даними
і натискає кнопку «Відправити»;


|Система|

: Система перевіряє поля на заповненість
та введені дані на достовірність;

note right #aaffaa

<font color=red><b> Можливо EX_00.
<font color=red><b> Можливо EX_01.

end note

: Система розміщує нову публікацію;

stop;
@enduml
