@startuml
left header
<font color=000 size=18><b>Package:</b> User
<font color=000 size=16><b>ID:</b> UC6
<font color=000 size=16><b>Назва:</b> Бронювання
<font color=000 size=16><b>Учасники:</b> Користувач, Система
<font color=000 size=16><b>Передумови:</b> Користувач бажає забронюватии послугу
<font color=000 size=16><b>Результат:</b> Послугу заброньовано
<font color=000 size=16><b>Виключні ситуації:</b>
<font color=000 size=16>EX_00: Некоректний запит
<font color=000 size=16>EX_01: Доступ до бази даних відсутній
<font color=000 size=16>EX_02: Некоректно введені дані
<font color=000 size=16><b>Основний сценарій:</b>
end header

skinparam	shadowing false
skinparam Note {
	BackgroundColor #f85658
	FontColor #ffffff
}

|Користувач|
start
: Натискає кнопку «Забронювати»;


|Система|
: Отримує дані про послугу, яку намагається забронювати користувач;
note right
Можливо ЕХ_00
end note
note right
Можливо ЕХ_01
end note

: Перенаправляє користувача на сторінку системи бронювання;

|Користувач|
: Вводить запитувані дані;

|Система|
: Обробляє дані;

: Оновлює дані про послугу, яку бронював користувач;
note right
Можливо ЕХ_01
end note
note right
Можливо ЕХ_02
end note

: Надсилає повідомлення про вдале бронювання;

|Користувач|
: Отримує підтвердження вдалого бронювання;

stop;
@enduml
