@startuml
left header

<font color=000 size=16><b>Назва:</b> Рейтингова оцінка закладу/місця.
<font color=000 size=16><b>Учасники:</b> Авторизований користувач, Система.
<font color=000 size=16><b>Передумови:</b> Користувач авторизований.
<font color=000 size=16><b>Результат:</b> Змінюється рейтинг закладу/місця.

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Авторизований користувач|
start

: Користувач натискає на відповідну мітку рейтингу закладу/місця;

|Система|

: Система записує оцінку користувача до бази даних;

: Система перераховує рейтинг закладу/місця;

: Система відображає оновлений рейтинг закладу/місця;

stop;
@enduml
