@startuml
left header
<font color=000 size=18><b>Package:</b> User
<font color=000 size=16><b>ID:</b> UC5
<font color=000 size=16><b>Назва:</b> Збереження
<font color=000 size=16><b>Учасники:</b> Користувач, Система
<font color=000 size=16><b>Передумови:</b> Користувач бажає зберегти вподобану публікацію
<font color=000 size=16><b>Результат:</b> Публікацію додано до списку збережених користувача
<font color=000 size=16><b>Виключні ситуації:</b>
<font color=000 size=16>EX_00: Некоректний запит
<font color=000 size=16>EX_01: Доступ до бази даних відсутній
<font color=000 size=16><b>Основний сценарій:</b>
end header

skinparam	shadowing false
skinparam Note {
	BackgroundColor #f85658
	FontColor #ffffff
}

|Користувач|
start
: Натискає кнопку «Зберегти»;


|Система|
: Оновлює  розділ «Збережені публікації»;
note right
Можливо ЕХ_01
end note
note right
Можливо ЕХ_00
end note


|Користувач|
: Отримує повідомлення про вдале збереження публікації;

stop;
@enduml
