@startuml 

left header
<font color=000 size=18><b>Package:</b> User
<font color=000 size=16><b>ID:</b> UC1
<font color=000 size=16><b>Назва:</b> Реєстрація нового користувача 
<font color=000 size=16><b>Учасники:</b> Користувач, Система
<font color=000 size=16><b>Передумови:</b> Користувач бажає зареєструватися
<font color=000 size=16><b>Результат:</b> Данні користувача оброблено й збережено в базі, додано новий обліковий запис
<font color=000 size=16><b>Виключні ситуації:</b>
<font color=000 size=16>EX_00: Некоректний запит
<font color=000 size=16>EX_01: Доступ до бази даних відсутній
<font color=000 size=16>EX_02: Некоректно введені дані
<font color=000 size=16><b>Основний сценарій:</b>
end header

skinparam	shadowing false
skinparam Note {
	BackgroundColor #f85658
	FontColor #ffffff
}

|Користувач|
start
: Натискає кнопку «Реєстрація»;

: Dводить ПІБ та поштову адресу;

|Система|
: Оброблює дані;

: Надсилає на пошту повідомлення із кодом підтвердження;

: Перевіряє правильність введеного коду;

|Користувач|
:Додає інформацію про себе;

|Система|
:Оброблює дані користувача;

:Створює обліковий запис;

|Користувач|
:Отримує повідомлення про вдалу реєстрацію;
stop;
@enduml
