# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "vagrant-centos7"
  config.vm.define "centos7"

  config.vm.provider "qemu" do |qemu|
    qemu.arch = "x86_64"
    qemu.machine = "q35"
    qemu.cpu = "max"
    qemu.net_device = "virtio-net-pci"
    qemu.extra_qemu_args = %w(-accel tcg,thread=multi,tb-size=512)
    qemu.ssh_port = 3024
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "site.yml"
    ansible.inventory_path = "inventory/"
    ansible.host_key_checking = false
    ansible.limit = "vagrant"
  end

end
