@startuml
left header
<font color=000 size=18><b>Package:</b> Agent

<font color=000 size=16><b>ID:</b> UC-2
<font color=000 size=16><b>Назва:</b> Редагування публікації
<font color=000 size=16><b>Учасники:</b> Представник, Адміністратор, Система.
<font color=000 size=16><b>Передумови:</b> Представник бажає змінити дані у публікації.
<font color=000 size=16><b>Результат:</b> Дані у публікації змінено.

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Представник|
start
: Представник редагує публікацію;

: Представник надсилає запит про оновлення даних публікацїї;


|Система|
: Система обробляє отримані дані;

|Адміністратор|
: Адміністратор схвалює внесені зміни;

|Система|
: Дані публікації оновлено;

stop;
@enduml