@startuml
entity Користувач {
    "ім'я",
    "електронна пошта",
    "пароль"
    "тип користувача"
}

entity Оцінка {
    "значення"
}
entity Коментар {
    "зміст"
}
entity Публікація {
    "назва",
    "зміст",
    "статус верифікації"
}
entity Звернення {
    "зміст"
}

Користувач "1,1"<-->"0,*" Публікація
Публікація "1,1"<-->"0,*" Оцінка
Публікація "1,1"<-->"0,*" Коментар
Користувач "1,1"<-->"0,*" Оцінка
Користувач "1,1"<-->"0,*" Коментар
Користувач "1,1"<-->"0,*" Звернення
@enduml
