@startuml

entity Гість 

entity Користувач {
    "ім'я",
    "електронна пошта",
    "пароль"
}
entity Представник {
    "ім'я",
    "електронна пошта",
    "пароль"
}
entity Адміністратор {
    "ім'я",
    "електронна пошта",
    "пароль"
}
entity Служба {
    "ім'я",
    "електронна пошта",
    "пароль"
}


entity Оцінка {
    "значення",
    "автор"
}
entity Коментар {
    "зміст",
    "автор"
}
entity Публікація {
    "назва",
    "зміст",
    "автор",
    "оцінки",
    "коментарі",
    "статус верифікації"
}
entity Звернення {
    "зміст",
    "автор"
}

@enduml
