@startuml
left header

<font color=000 size=16><b>Назва:</b> Звернення до служби підтримки.
<font color=000 size=16><b>Учасники:</b> Користувач, Служба підтримки.
<font color=000 size=16><b>Передумови:</b> У користувача з'явилося питання щодо роботи Системи.
<font color=000 size=16><b>Результат:</b> Питання користувача вирішено.

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Користувач|
start
: Користувач натискає спеціальну кнопку "Служба підтримки" у модулі "Обліковий запис";
: Заповнює поля "Тема" та "Опис проблеми" у вікні що з'явилося;
: Натискає кнопку "Відправити";

|Служба підтримки|
: Отримує повідомлення користувача;
: Вирішує проблему користувача;
: Надсилає відповідь Користувачу на електронну пошту;

|Користувач|

: Отримує електронного листа з відповіддю на своє питання;

|Користувач|
stop;
@enduml
