@startuml
left header
<font color=000 size=18><b>Package:</b> Guest

<font color=000 size=16><b>ID:</b> UC-1
<font color=000 size=16><b>Назва:</b> Пошук публікацій
<font color=000 size=16><b>Учасники:</b> Гість, Система
<font color=000 size=16><b>Передумови:</b> Гість хоче знайти інформацію про заклад та відгуки
<font color=000 size=16><b>Результат:</b> Гість отримує інформацію про заклад та відгуки

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Гість|
start
: Натискає кнопку «Пошук»;

: Вводить запит;


|Система|
: Отримує запит, обробляє його та відображає результати пошуку;

|Гість|
: Отримує результати пошуку;
: Публікація знайдена, гість може проглядати фото та читати коментарі;
stop;

right footer

Четверта підгрупа. Модель прецендентів
НТУУ КПІ ім.І.Сікорського
Киів-2020
end footer
@enduml
