@startuml
left header
<font color=000 size=18><b>Package:</b> Guest

<font color=000 size=16><b>ID:</b> UC-3
<font color=000 size=16><b>Назва:</b> Реєстрація представника
<font color=000 size=16><b>Учасники:</b> Гість, Система, Адміністратор
<font color=000 size=16><b>Передумови:</b> Гість хоче створити обліковий запис представника
<font color=000 size=16><b>Результат:</b> Гість створює обліковий запис представника
<font color=000 size=16><b>Виключні ситуації:</b>
<font color=000 size=16> EX_00: Користувач с такими даними вже існує
<font color=000 size=16> EX_01: Код було введено неправильно  
<font color=000 size=16> EX_02: Паролі не збігаються
<font color=000 size=16> EX_03: Доступ до бази даних відсутній
<font color=000 size=16> EX_04: Адміністратор відмінив запит

<font color=000 size=16><b>Основний сценарій:</b>

end header

|Гість|
start
: Натискає на кнопку "Обліковий запис" у головному меню;
: Натискає на кнопку "Реєстрація";
: Обирає тип облікового запису "Представник";
: Заповнює ФІО та поштову адресу;


|Система|
: Надсилає лист із кодом підтвердження на вказану поштову адресу;
note left #aaffaa
<font color=red><b> Можливо EX_00
end note

|Гість|
: Отримує код та вводить його у поле для коду;

: Заповнює інформацію про заклад: назва, розташування, власник, документи та створює пароль;


|Система|
: Записує дані до бази та відправляє запит до адміністратора;
note right #aaffaa

<font color=red><b> Можливо EX_02
end note
note left #aaffaa
<font color=red><b> Можливо EX_01
end note
note left #aaffaa
<font color=red><b> Можливо EX_03
end note

|Адміністратор|
: Отримує запит;
note right #aaffaa
<font color=red><b> Можливо EX_04
end note
stop;

right footer

Четверта підгрупа. Модель прецендентів
НТУУ КПІ ім.І.Сікорського
Киів-2020
end footer
@enduml
