apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  serviceName: "mysql"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels: 
        app: mysql
    spec:
      containers: 
      - name: mysql
        image: mysql:8
        resources:
          limits :
            cpu: 1000m
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: muchsecurity
        - name: MYSQL_DATABASE
          value: bookstore
        ports: 
        - containerPort: 3306
          name: mysql
        volumeMounts:
          # name must match the volume name below
        - name: mysql-persistent-storage
          # mount path within the container
          mountPath: /var/lib/mysql
      # Simulate persistent storage
      volumes:
      - name: mysql-persistent-storage
        emptyDir: {}
